server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  datasource:
    username: neondb_owner
    password: MuqxTpf29WGF
    url: jdbc:postgresql://ep-fragrant-morning-a550jy3t.us-east-2.aws.neon.tech/neondb?useSSL=false
  mail:
      host: mail.rtb.gov.rw
      port: 587
      properties:
        mail:
            smtp:
              auth: true
            starttls:
                enable: true
      username: tvettrainerrecruitment@rtb.gov.rw
      password: Tvet@Recruitment#2023

springdoc:
  api-docs:
    enabled: true
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
    path: /v3/api-docs

jwt:
  jwtSecret: ${JWT_SECRET:yourverylongandverysecuresecretkeyherediuqwhduiqwhduiqwhqwuidhqwuidqhwduiqwhdquiwdqwfiojasiofjasoifjasfioaj}
  expiration: 3600000
invitation:
  valid:
    days: 7

app:
  registration:
    code: 123456
    fronted: ${FRONTED:http://128.140.67.37:3000}
  host: ${HOST:http://128.140.67.37:8081}

uploads:
    extensions: pdf,png,jpeg,jpg
    directory: /opt/cozystay
    files: /opt/uploads/files

logging:
  level:
    root: INFO
    org.apache.tomcat: INFO
    org.apache.catalina: INFO